#!/bin/bash

# Verificar si el usuario es superusuario (root)
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 
   exit 1
fi

# Función para iniciar los servicios
start_services() {
    echo "Starting services..."
    systemctl start apache2
    systemctl start mariadb
    systemctl start proftpd
}

# Función para detener los servicios
stop_services() {
    echo "Stopping services..."
    systemctl stop apache2
    systemctl stop mariadb
    systemctl stop proftpd
}

# Función para reiniciar los servicios
restart_services() {
    echo "Restarting services..."
    systemctl restart apache2
    systemctl restart mariadb
    systemctl restart proftpd
}

# Función para verificar el estado de los servicios
status_services() {
    echo "Services Status:"
    echo -n "Apache: "
    systemctl is-active --quiet apache2 && echo "Running" || echo "Not running"
    echo -n "MariaDB: "
    systemctl is-active --quiet mariadb && echo "Running" || echo "Not running"
    echo -n "ProFTPD: "
    systemctl is-active --quiet proftpd && echo "Running" || echo "Not running"
}

# Validar los argumentos de entrada
case "$1" in
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        restart_services
        ;;
    status)
        status_services
        ;;
    *)
        echo "Usage: webserver {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0

